title: Givey Knowledge Base

markdown: kramdown

collections:
  articles:
    output: true
    permalink: /articles/:path

exclude:
- bin
- Gemfile*
- assets/bower
- package.json
- bower.json
- node_modules
- npm-debug.log
- Gruntfile.js
